if: tag IS blank
git:
  depth: 1
sudo: false
language: node_js
node_js:
  - "8"
  - "9"

before_install:
  - npm install -g lerna@3.0.0-beta.0

install:
  - lerna bootstrap --registry=https://registry.npmjs.org/

script:
  - commitlint-travis
  - lerna run test
